# Generated by Django 4.1.3 on 2022-11-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_blogindexpage_blogpage_blogpageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=350)),
            ],
        ),
    ]
