# Generated by Django 4.1.3 on 2022-11-15 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_contactpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='Contact',
        ),
    ]
