# Generated by Django 4.1.3 on 2022-11-15 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_rename_forms_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
