# Generated by Django 4.1.3 on 2022-11-16 08:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_alter_aboutpage_creator_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_abstract',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
