# Generated by Django 4.1.3 on 2022-11-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_blogpage_blog_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('IsActive', models.BooleanField(null=True)),
            ],
        ),
    ]
