# Generated by Django 4.1.3 on 2022-11-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_workdetailspage_workdetailspagethumbnailimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetailspagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='workdetailspagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='workdetailspagethumbnailimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='workdetailspagethumbnailimage',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
        migrations.DeleteModel(
            name='WorkDetailsPage',
        ),
        migrations.DeleteModel(
            name='WorkDetailsPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='WorkDetailsPagethumbnailImage',
        ),
    ]
